etalab/entreprise.api.gouv.fr

_config.yml
_includes/footer.html

Ajout du lien vers les CGUs dans le footer 

---

.github/pull_request_template.md

merge template_pr into master

---

_layouts/myhome.html

Ajout d'une section sur la page d'accueil avec un lien vers entreprise.data.gouv.fr
Pour les entreprises privées ils faut les rediriger vers entreprise.data.gouv.fr sans qu'on ait à traiter des mails de support

Add link to data gouv in a new section

---

pages/mentions.md

Ajout des coordonnées du DPD. Comme @odtvince l'a suggéré ça sera les informations présente sur https://www.gouvernement.fr/contacter-delegue-protection-donnees-dpd
J'ai préféré copier les informations plutôt que mettre un lien. Ok ?

merge add_dpd into master

---

_layouts/myhome.html

C'est succinct, je suis preneur si vous avez une meilleure catch phrase ou que vous voulez rajouter quelque chose.
WDYT ?

Update website baseline

---

_sass/stats.scss
pages/stats.html

Ajout des statistiques d'utilisations annuelle
Ajouts de stats pour plus de visibilité
closes #22

Yearly stats

---

_providers/inpi.md

INPI add acte & bilan

---

_layouts/faq.html
_layouts/page.html
pages/mentions.md

Retire du contenu dupliqué et utilise un meilleur layout

Corrige les mentions legales

---

_includes/head.html

La PR affiche le titre configuré pour le site.

Afficher le titre

---

_catalogue/attestation-de-vigilance.md
_catalogue/conformité-emploi-des-travailleurs-handicapés.md
_catalogue/données-de-référence-dun-établissement.md
_catalogue/déclarations-de-résultats.md

Relecture de la documentation avant déploiement
Il y a quelques éléments que je n'ai pas touchés, notamment le header avec les options de recherches mais j'ai quelques commentaires : 
* "Chercher une information" je remplacerai par "filtrer une information" je trouve que c'est plus en accord avec la fonctionnalité. 
* "Cas d'usage" => "Tous les cas d'usage"
* "Fournisseurs" => "Tous les fournisseurs" (cela fait plus sens après avoir choisi un élément de la liste pour filtrer quand on souhaite revenir en arrière pour avoir *tous* les résultats) 
* il est mieux d'essayer de ne pas utiliser de possessifs comme "nos APIs", "nous renvoyons la données", etc et d'utiliser le terme "API Entreprise" : "API Entreprise propose...", "API Entreprise ne transmet pas la données..." etc.
J'ai fait une …

Reword and update doc

---

_includes/head.html
config/deploy.rb
netlify.toml

J'ouvre une PR vu que je ne suis pas sûr que tout se passe bien + potentiellement il faudra
checker la config.

Utilisation de jekyll.environment

---

_catalogue/donnees-de-reference.md

Elle ajoute les derniers échanges avec l'INSEE concernant les entreprises qui peuvent être actives malgré que l'ensemble de leurs établissements soit fermés.
Compléter la doc

Modification contenu entreprise insee

---

_catalogue/donnees-de-reference.md
_catalogue/données-de-référence-dun-établissement.md
_sass/catalogue.scss
pages/catalogue.html

Cf https://3.basecamp.com/4318089/buckets/14906626/todos/3138668804

Permet d'ajouter des FAQ aux fournisseurs de données.

---

_catalogue/effectifs-annuel-dune-entreprise.md
assets/js/catalogue.js

Elle ajoute la documentation de l'endpoint effectif acoss dans le catalogue.
Cet endpoint pourtant bien en prod n'a pas de doc actuellement.

Ajout endpoint acoss effectifs

---

.gitignore
Gemfile
Gemfile.lock
_config.yml
_layouts/default.html
_sass/support.scss
_supports/090-candidatures.md
assets/js/main.js
bin/algolia_indexer.rb
config/deploy.rb
pages/support.html

Ajout de la recherche algolia sur le support

Support recherche

---

Gemfile
Gemfile.lock
README.md
_config.yml
_layouts/documentation.html
_sass/algolia.scss
_sass/default.scss
_sass/documentation.scss
_sass/support.scss
assets/js/documentation.js
assets/js/links.js
bin/algolia_indexer.rb
pages/documentation.html

https://3.basecamp.com/4318089/buckets/14906626/todos/3129670895

Introduce search on documentation

---

README.md
_documentation/démarrer-avec-api-entreprise.md
_documentation/les-prérequis-techniques-avant-d’aller-plus-loin.md
_layouts/home.html

Juste quelques petits changements sur de la typo, notamment dans le domaine du service.

Petits fixes sur des erreurs de typo

---

_layouts/home.html
_sass/home.scss
_sass/support.scss
_use_cases/aides_publiques.md
_use_cases/covid_19.md
_use_cases/marches_publics.md
assets/js/home.js
assets/js/support.js
bin/algolia_indexer.rb
pages/support.html

* Ajout de l'indexation (minimal) du catalogue
* Recherche globale sur la home page
https://3.basecamp.com/4318089/buckets/14906626/todos/3469013987
-------------
Breakdown:

Introduce global search on home page

---

_layouts/home.html
_sass/home.scss

[OVH] Notification Incident

---

_catalogue/attestation-de-vigilance.md
_catalogue/attestation-fiscale.md
_catalogue/bilans-annuels-3-dernières-années.md
_catalogue/bilans-annuels.md
_catalogue/chiffre-d-affaires.md
_catalogue/conformité-emploi-des-travailleurs-handicapés.md
_catalogue/cotisations-congés-payés-chômage-intempéries.md
_catalogue/cotisations-de-sécurité-sociale-agricole.md
_catalogue/donnees-de-reference.md
_catalogue/données-de-référence-dun-établissement.md
_catalogue/déclarations-de-résultats.md
_catalogue/effectifs-dune-entreprise.md
_catalogue/extrait-rcs.md
_catalogue/import-export-en-union-européenne-eori-douanes.md
_catalogue/éligibilité-cotisations-retraite-probtp.md
_config.yml
_documentation/démarrer-avec-api-entreprise.md
_documentation/lapi-entreprise-correspond-elle-à-mon-besoin.md
_layouts/home.html
_sass/home.scss
_use_cases/aides_publiques.md
_use_cases/covid_19.md
_use_cases/editeurs.md
_use_cases/marches_publics.md
_use_cases/preremplissage_public.md
_use_cases/preremplissage_securise.md
admin/config.yml

- renommage "données confidentielles" par "données protégées"
- suppression bandeau incident OVH

Merge sandbox

---

_catalogue/déclarations-de-résultats.md

Ajout d'infos concernant les imprimés identiques

Liasse fiscale DGFIP

---

_catalogue/donnees-de-reference.md
_catalogue/données-de-référence-dun-établissement.md

Fix non_diffusableS (plural)

---

_config.yml
_data/footer.yml
_data/header.yml
_includes/head.html
_includes/header.html
_layouts/newsletters.html
_newsletters/2020-03-05-infolettre.md
_newsletters/2020-03-09-insee.md
_newsletters/2020-06-09-infolettre.md
_newsletters/2020-07-22-dgfip.md
_newsletters/2020-09-30-infolettre.md
_newsletters/2021-01-20-dgfip.md
_newsletters/2021-01-26-volumetrie.md
_newsletters/2021-02-10-infolettre.md
_newsletters/2021-03-10-incident-ovh.md
_sass/components/dropdown.scss
_sass/default.scss
_sass/main.scss
_sass/newsletters.scss
pages/infolettres.html

BD:
---------------------
Nouvelle page pour lister toute notre communication externe
https://3.basecamp.com/4318089/buckets/14906626/todos/3464838683
https://3.basecamp.com/4318089/buckets/21167830/documents/3538182035
https://3.basecamp.com/4318089/projects/21167830
-
Pour le moment se rendre sur /infolettres/
-> https://deploy-preview-101--api-entreprise-sandbox.netlify.app/infolettres/
Potentiellement mailjet

Introduce newsletters

---

_layouts/home.html

Ajout du logo de l'ADEME sur la page d'accueil

Add ADEME logo

---

_catalogue/donnees-de-reference.md
_catalogue/données-de-référence-dun-établissement.md

Elle propose d'ajouter dans la doc des éléments de contenus donnés par l'INSEE lors du Webinaire du 30 mars 15h. Webinaire coorganisé par l'API Entreprise et l'INSEE
Pour compléter la documentation

Ajout d'information dans les docs INSEE suite au Webinaire

---

README.md
_config.yml
_data/popup.yml
_includes/head.html
_includes/popup.html
_layouts/default.html
_sass/components/micromodal.scss
_sass/default.scss

Wait some times and display only once by session (cookie stored a modal)
to users (numéro de pacage).
This is tracked on Matomo too.
Install micromodal and js-cookie

Introduce popup system

---

_catalogue/actes.md
_catalogue/attestation-de-vigilance.md
_catalogue/attestation-fiscale.md
_catalogue/bilans-annuels-3-dernières-années.md
_catalogue/bilans-annuels.md
_catalogue/brevets-modèles-et-marques-déposés.md
_catalogue/carte-professionnelle-travaux-publics.md
_catalogue/certificat-de-qualification-bâtiment.md
_catalogue/certification-de-qualification-dingénierie.md
_catalogue/certification-rge.md
_catalogue/certifications-en-bio.md
_catalogue/chiffre-d-affaires.md
_catalogue/conformité-emploi-des-travailleurs-handicapés.md
_catalogue/conventions-collectives.md
_catalogue/cotisations-congés-payés-chômage-intempéries.md
_catalogue/cotisations-de-sécurité-sociale-agricole.md
_catalogue/divers-documents-dune-association.md
_catalogue/donnees-de-reference-entreprise-artisanale.md
_catalogue/donnees-de-reference.md
_catalogue/données-de-référence-dun-établissement.md
_catalogue/déclarations-de-résultats.md
_catalogue/effectifs-dune-entreprise.md
_catalogue/extrait-rcs.md
_catalogue/import-export-en-union-européenne-eori-douanes.md
_catalogue/informations-déclaratives-d’une-association.md
_catalogue/éligibilité-cotisations-retraite-probtp.md
_documentation/démarrer-avec-api-entreprise.md

Elle met à jour le catalogue avec les nouvelles règles de volumétrie

MAJ volumétrie catalogue

---

_catalogue/données-de-référence-dun-établissement.md

Corrige la documentation de /etablissements qui était complètement fausse ?! 
Un utilisateur l'a remarqué...

fix: WRONG documentation for /etablissements

---

_data/popup.yml

we have enought insights already
users don't understand what this is about

Disable popup for pacage

---

_documentation/démarrer-avec-api-entreprise.md
_documentation/les-prérequis-techniques-avant-d’aller-plus-loin.md

Elle ajoute le contenu dans la documentation permettant de présenter la fonctionnalité "magic link" à l'utilisateur

Doc nouvelle fonctionnalité magic link

---

_use_cases/aides_publiques.md

Elle ajoute l'éditeur Atexo à la liste des éditeurs du cas d'usage aides publiques

Ajoute l'éditeur Atexo

---

_supports/050-connection-dashboard.md

Paragraphe concernant l'envoi possible d'un magic link pour accéder au jeton.
Cette FAQ aura un rôle important puisqu'elle sera mise en lien dans la partie authentification du dashboard. Il est important que tous les cas de figure y soient présents

Ajoute un contenu dans la faq concernant le magic link

---

_sass/support.scss
assets/js/support.js
pages/support.html

Ajout de permalinks sur les éléments du support pour simplifier le partage des infos (notamment pour le support).

Add permalinks on support

---

_config.yml
_includes/head.html
pages/catalogue.html
pages/documentation.html

Affinage et mise à jours des données open graph pour les moteurs de recherche
https://3.basecamp.com/4318089/buckets/14906626/todos/3927003349
https://3.basecamp.com/4318089/buckets/14906626/todos/3927081785
https://3.basecamp.com/4318089/buckets/14906626/todos/3927069613

Update metadata for search enfines

---

_catalogue/attestation-de-vigilance.md
_catalogue/cotisations-de-sécurité-sociale-agricole.md

Elle propose de mettre à jour la doc de l'attestation de vigileance
Car le périmètre à évoluer depuis le 17 mars dernier.

Maj doc Attestation vigileance (OETH)

---

_documentation/api-entreprise-au-quotidien.md

Elle propose de supprimer de la doc ce qui est en rapport avec l'ancien mode de connexion démarches simplifiées

Mise à jour doc - suppression allusion à démarches simplifiées

---

_data/notification.yml

Elle ajoute temporairement une notification pour annoncer la page statut et la possibilité de s'abonner.

Ajout notification pour la nouvelle page de statut

---

config/deploy.rb

Mise à jour de la base de signatures Samhain lors du déploiement.
Cette opération prend de l'ordre de 5 minutes. Cela ne ralentit pas le déploiement applicatif au sens strict  car elle a lieu une fois les fichiers déployés, mais rend l'exécution de la tâche de déploiement plus longue.
On met en place le détecteur d'intrusion Samhain sur toutes les machines.
Sa vérification principale consiste à maintenir une liste des fichiers du système et à alerter en cas de modification. Cette MR permet d'éviter que Samhain n'alerte lors du déploiement, qui est une modification légitime.
Tester le déploiement.

Mise à jour signatures Samhain lors du déploiement

---

config/deploy.rb

Et aussi modernisation de l'appel à la mise à jour de base Samhain.

Ajustement déploiement à la suppression de l'accès SSH au compte deploy
